[Configuration]
name = "My Configuration"

[[Room]]
name="LL"
  [[Room.Rack]]
  name = "Rack1"
    
    [[Room.Rack.Crate]]
    name = "My Crate "
      
      [[Room.Rack.Crate.Board]]
      name = "titi"
      type = "N141X"
      
      [Room.Rack.Crate.Board.Connector]
        name = "Connector 1"
        Type = "CAENVME"
        Model = "V1718"
        "Link Number" = 0


