language: cpp

sudo: required

dist: bionic
osx_image: xcode11.2

compiler:
  - gcc
  - clang
  
os:
  - linux
  - osx
  - windows
  
before_install:
  - $CXX --version
  - $CC --version

  - if [ $TRAVIS_OS_NAME == linux ]; then wget https://root.cern/download/root_v6.18.02.Linux-ubuntu18-x86_64-gcc7.4.tar.gz && tar -xvf root_v6.18.02.Linux-ubuntu18-x86_64-gcc7.4.tar.gz && source root/bin/thisroot.sh; fi  

  - if [ $TRAVIS_OS_NAME == osx ]; then wget https://root.cern/download/root_v6.18.02.macosx64-10.14-clang100.tar.gz && tar -xvf root_v6.18.02.macosx64-10.14-clang100.tar.gz && source root/bin/thisroot.sh; fi  
  
  - if [ $TRAVIS_OS_NAME == windows ]; then wget https://root.cern/download/root_v6.18.02.win32.vc16.debug.zip && tar -xvf https://root.cern/download/root_v6.18.02.win32.vc16.debug.zip && source root/bin/thisroot.sh; fi 

  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update; fi
 
  
install:
  # Install package dependencies for Linux:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y python-numpy-dev ; fi
  # Install package dependencies for Mac OS X:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew unlink cmake; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install python libusb qt; fi
  # Install numpy via pip:
  - if [ $TRAVIS_OS_NAME == osx ]; then easy_install pip && pip install numpy; fi
  
before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake lcov doxygen ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake lcov doxygen; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then source $(brew --prefix root)/libexec/thisroot.sh; fi
  - $CXX --version
  - $CC --version
  - mkdir build
  - cd build

  
script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake .. ;  fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_COMPILER" = "clang" ]; then cmake .. ;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_COMPILER" = "gcc" ]; then cmake -DCMAKE_BUILD_TYPE=Coverage .. ;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake .. ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake --build . ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_COMPILER" = "clang" ]; then cmake --build . ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_COMPILER" = "gcc" ]; then cmake --build . --target coverage ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake --build . ; fi
  - cmake --install .
  # if the project uses ctest we can run the tests like this
  # - make test
  # - make docs 
  
#after_success:
# Create lcov report
# capture coverage info
# - lcov --directory . --capture --output-file coverage.info
# filter out system and extra files.
# To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
# - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
# output coverage data for debugging (optional)
# - lcov --list coverage.info
# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
# - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
