
# Copyright (c) 2019-2020 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: Windows
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  triplet: x64-windows
  vcpkgCommitId: 'c7ab9d3110813979a873b2dbac630a9ab79850dc'
  vcpkgPackages: 'zlib'
  configuration: 'x64.*'

jobs:
  job:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: lukka/get-cmake@master
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Restore artifacts, or Run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@master
        id: runvcpkg
        with:
          vcpkgArguments: '${{ env.vcpkgPackages }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgTriplet: '${{ env.triplet }}'
          vcpkgGitCommitId: '${{ env.vcpkgCommitId }}'
      - name: Prints output of run-vcpkg's task
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}' "
      - name: Run CMake+Ninja
        uses: lukka/run-cmake@master
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
          cmakeAppendedArgs: '-G Ninja -DBUILD_ANALYSIS=OFF -DBUIL_OLD_WAVEDUMP=OFF'
      #- name: Run CMake+VS
      #  uses: lukka/run-cmake@master
      #  with:
      #    cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
      #    cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
      #    useVcpkgToolchainFile: true
      #    buildDirectory: '${{ runner.workspace }}/b/vs16'
      #    cmakeAppendedArgs: '-G"Visual Studio 16 2019" -Ax64'
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
